sudo: required
dist: xenial
group: edge
language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_script:
  - composer config -g github-oauth.github.com ${GH_TOKEN}
  - composer self-update
  - composer install --no-interaction
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'hhvm.php7.all = 1' >> /etc/hhvm/php.ini; fi
  - if [[ $TRAVIS_PHP_VERSION =~ ^7 ]]; then git clone git://github.com/xdebug/xdebug.git && cd xdebug && phpize && ./configure --enable-xdebug  && make && make install && echo "zend_extension = xdebug.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini && cd ..; fi

script:
  - vendor/bin/phpcs
  - bin/kahlan --config=kahlan-config.travis.php --clover=clover.xml

after_success:
  - "if [ $(phpenv version-name) = '7.0' ]; then curl -X POST -d @codeclimate.json -H 'Content-Type:application/json' https://codeclimate.com/test_reports --verbose; fi"
  - "if [ $(phpenv version-name) = '7.0' ]; then curl -F 'json_file=@coveralls.json' https://coveralls.io/api/v1/jobs --verbose; fi"
  - "if [ $(phpenv version-name) = '7.0' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - "if [ $(phpenv version-name) = '7.0' ]; then php ocular.phar code-coverage:upload --format=php-clover 'clover.xml'; fi"

env:
  global:
    secure: TNBFgKzPmRdD79Raor5vvsvwZ1EkxFjP88QA2sBlKKzzn+BarErG9FVnrF/wGFvozHmGF4PKGIINuc1FQ1RDe6SgxaaXWxfaUs8FGz3RUv7O6Zu1wssLlFh2kpzwKjweqgwOlsVP6ATPz299tP8CGen8DPMpaUXd0l+RI5+4B6c=
