language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

matrix:
  fast_finish: true
  allow_failures:
    # PHP 7 is still in active development.
    - php: 7.0

before_script:
  - composer self-update && composer install --no-dev
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'xdebug.enable = On' >> /etc/hhvm/php.ini; fi
  #- if [[ $TRAVIS_PHP_VERSION =~ ^7 ]]; then pecl install xdebug; fi

script: bin/kahlan --config=kahlan-config.travis.php --clover=clover.xml

after_success:
  - "if [ $(phpenv version-name) = '5.6' ]; then curl -X POST -d @codeclimate.json -H 'Content-Type:application/json' https://codeclimate.com/test_reports --verbose; fi"
  - "if [ $(phpenv version-name) = '5.6' ]; then curl -F 'json_file=@coveralls.json' https://coveralls.io/api/v1/jobs --verbose; fi"
  - "if [ $(phpenv version-name) = '5.6' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - "if [ $(phpenv version-name) = '5.6' ]; then php ocular.phar code-coverage:upload --format=php-clover 'clover.xml'; fi"
